name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Tool versions
      run: |
        cargo --version
        rustup --version
    - uses: actions/checkout@v5
    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Format
      run: cargo fmt --check
    - name: Clippy linting
      run: cargo clippy --no-deps --all-targets --all-features
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
